# Generated by Django 5.1.5 on 2025-08-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(max_length=20)),
                ('assignee_login', models.CharField(blank=True, max_length=100)),
                ('repository_name', models.CharField(max_length=200)),
                ('repository_owner', models.CharField(max_length=100)),
                ('html_url', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('synced_to_notion', models.BooleanField(default=False)),
                ('notion_page_id', models.CharField(blank=True, max_length=100)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_locally', models.DateTimeField(auto_now_add=True)),
                ('updated_locally', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub Issue',
                'verbose_name_plural': 'GitHub Issues',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Manual Sync'), ('scheduled', 'Scheduled Sync'), ('webhook', 'Webhook Triggered')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('issues_processed', models.IntegerField(default=0)),
                ('issues_synced', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('error_messages', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
